# Generated by Django 4.0 on 2024-07-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_order_products'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0007_alter_baseuser_options_alter_rentplace_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='buyed_products',
            field=models.ManyToManyField(related_name='users_buy', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='cart',
            field=models.ManyToManyField(related_name='users_carted', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
